/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hq.mobydroid.gui;

import com.hq.materialdesign.MaterialIcons;
import com.hq.mobydroid.MobydroidStatic;
import com.hq.mobydroid.Settings;
import javax.swing.JOptionPane;

/**
 *
 * @author Bilux (i.bilux@gmail.com)
 */
public class JPanel_Settings extends javax.swing.JPanel {

    // ************************ My variable ************************
    // *************************************************************
    /**
     * Creates new form JPanel_ManageApps
     *
     */
    public JPanel_Settings() {
        // initialize components
        initComponents();
    }

    /**
     * Update device information
     */
    public void updateInfo() {
        // set
        jCheckBox_ExpertSettings.setSelected(Boolean.valueOf(Settings.get("Expert_Settings")));
        jCheckBox_SuRoot.setSelected(Boolean.valueOf(Settings.get("SuRoot")));
        jTextField_HomePath.setText(MobydroidStatic.MOBY_HOME_PATH);
        jTextField_LogPath.setText(MobydroidStatic.LOG_PATH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_LanguageIcon = new javax.swing.JLabel();
        jLabel_Language = new javax.swing.JLabel();
        jComboBox_Language = new javax.swing.JComboBox<>();
        jLabel_ExpertSettingsIcon = new javax.swing.JLabel();
        jLabel_ExpertSettings = new javax.swing.JLabel();
        jCheckBox_ExpertSettings = new javax.swing.JCheckBox();
        jLabel_HomePathIcon = new javax.swing.JLabel();
        jLabel_HomePath = new javax.swing.JLabel();
        jTextField_HomePath = new javax.swing.JTextField();
        jLabel_LogPathIcon = new javax.swing.JLabel();
        jLabel_LogPath = new javax.swing.JLabel();
        jTextField_LogPath = new javax.swing.JTextField();
        jLabel_SuRoot = new javax.swing.JLabel();
        jLabel_SuRootIcon = new javax.swing.JLabel();
        jCheckBox_SuRoot = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Screen Capture : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel_LanguageIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(24f));
        jLabel_LanguageIcon.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_LanguageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LanguageIcon.setText(String.valueOf(MaterialIcons.LANGUAGE));

        jLabel_Language.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_Language.setText("Language :");

        jComboBox_Language.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English" }));

        jLabel_ExpertSettingsIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(24f));
        jLabel_ExpertSettingsIcon.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_ExpertSettingsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ExpertSettingsIcon.setText(String.valueOf(MaterialIcons.BUILD));

        jLabel_ExpertSettings.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_ExpertSettings.setText("Expert settings :");

        jCheckBox_ExpertSettings.setBackground(new java.awt.Color(250, 250, 250));
        jCheckBox_ExpertSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ExpertSettingsActionPerformed(evt);
            }
        });

        jLabel_HomePathIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(24f));
        jLabel_HomePathIcon.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_HomePathIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_HomePathIcon.setText(String.valueOf(MaterialIcons.FOLDER));

        jLabel_HomePath.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_HomePath.setText("MobyDroid Home Folder :");

        jTextField_HomePath.setEditable(false);

        jLabel_LogPathIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(24f));
        jLabel_LogPathIcon.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_LogPathIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LogPathIcon.setText(String.valueOf(MaterialIcons.LANGUAGE));

        jLabel_LogPath.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_LogPath.setText("MobyDroid Log File Location :");

        jTextField_LogPath.setEditable(false);

        jLabel_SuRoot.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_SuRoot.setText("Su Root Permission :");

        jLabel_SuRootIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(24f));
        jLabel_SuRootIcon.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_SuRootIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_SuRootIcon.setText(String.valueOf(MaterialIcons.BUILD));

        jCheckBox_SuRoot.setBackground(new java.awt.Color(250, 250, 250));
        jCheckBox_SuRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_SuRootActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_LanguageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Language, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_LogPathIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_LogPath, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_HomePathIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_HomePath, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_ExpertSettingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ExpertSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_SuRootIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_SuRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_HomePath, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jTextField_LogPath, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jCheckBox_SuRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_ExpertSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jComboBox_Language, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_ExpertSettingsIcon, jLabel_HomePathIcon, jLabel_LanguageIcon, jLabel_LogPathIcon, jLabel_SuRootIcon});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_ExpertSettings, jLabel_HomePath, jLabel_Language, jLabel_LogPath, jLabel_SuRoot});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Language, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_LanguageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Language, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ExpertSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ExpertSettingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_ExpertSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SuRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_SuRootIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_SuRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_HomePath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_HomePathIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_HomePath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_LogPath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_LogPathIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_LogPath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_ExpertSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ExpertSettingsActionPerformed
        // save value
        Settings.set("Expert_Settings", String.valueOf(jCheckBox_ExpertSettings.isSelected()));
        Settings.save();
        // show warning
        JOptionPane.showMessageDialog(this, "You need to restart application for this change to take effect.", "Restart needed", JOptionPane.OK_OPTION, ResourceLoader.MaterialIcons_WARNING);
    }//GEN-LAST:event_jCheckBox_ExpertSettingsActionPerformed

    private void jCheckBox_SuRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_SuRootActionPerformed
        if (jCheckBox_SuRoot.isSelected()) {
            // show warning
            int result = JOptionPane.showConfirmDialog(this, "Su Root permission is dangder and for exprets only!\nAre you sure you want to activate it?", "Su Root Permission", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, ResourceLoader.MaterialIcons_WARNING);
            if (result == JOptionPane.YES_OPTION) {
                jCheckBox_SuRoot.setSelected(true);
            } else {
                jCheckBox_SuRoot.setSelected(false);
            }
        }
        // save value
        Settings.set("SuRoot", String.valueOf(jCheckBox_SuRoot.isSelected()));
        Settings.save();
    }//GEN-LAST:event_jCheckBox_SuRootActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_ExpertSettings;
    private javax.swing.JCheckBox jCheckBox_SuRoot;
    private javax.swing.JComboBox<String> jComboBox_Language;
    private javax.swing.JLabel jLabel_ExpertSettings;
    private javax.swing.JLabel jLabel_ExpertSettingsIcon;
    private javax.swing.JLabel jLabel_HomePath;
    private javax.swing.JLabel jLabel_HomePathIcon;
    private javax.swing.JLabel jLabel_Language;
    private javax.swing.JLabel jLabel_LanguageIcon;
    private javax.swing.JLabel jLabel_LogPath;
    private javax.swing.JLabel jLabel_LogPathIcon;
    private javax.swing.JLabel jLabel_SuRoot;
    private javax.swing.JLabel jLabel_SuRootIcon;
    private javax.swing.JTextField jTextField_HomePath;
    private javax.swing.JTextField jTextField_LogPath;
    // End of variables declaration//GEN-END:variables
}
