/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hq.mobydroid.gui;

import com.hq.materialdesign.MaterialIcons;
import com.hq.mobydroid.MobydroidStatic;
import com.hq.mobydroid.Settings;
import javax.swing.JOptionPane;

/**
 *
 * @author Bilux (i.bilux@gmail.com)
 */
public class JPanel_Settings extends javax.swing.JPanel {

    // ************************ My variable ************************
    // *************************************************************
    /**
     * Creates new form JPanel_ManageApps
     *
     */
    public JPanel_Settings() {
        // initialize components
        initComponents();
    }

    /**
     * Update device information
     */
    public void updateInfo() {
        // set
        jCheckBox_ExpressSettings.setSelected(Boolean.valueOf(Settings.get("Express_Settings")));
        jTextField_HomePath.setText(MobydroidStatic.MOBY_HOME_PATH);
        jTextField_LogPath.setText(MobydroidStatic.LOG_PATH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_LanguageIcon = new javax.swing.JLabel();
        jLabel_Language = new javax.swing.JLabel();
        jComboBox_Language = new javax.swing.JComboBox<>();
        jLabel_ExpressSettingsIcon = new javax.swing.JLabel();
        jLabel_ExpressSettings = new javax.swing.JLabel();
        jCheckBox_ExpressSettings = new javax.swing.JCheckBox();
        jLabel_HomePathIcon = new javax.swing.JLabel();
        jLabel_HomePath = new javax.swing.JLabel();
        jTextField_HomePath = new javax.swing.JTextField();
        jLabel_LogPathIcon = new javax.swing.JLabel();
        jLabel_LogPath = new javax.swing.JLabel();
        jTextField_LogPath = new javax.swing.JTextField();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Screen Capture : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel_LanguageIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(24f));
        jLabel_LanguageIcon.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_LanguageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LanguageIcon.setText(String.valueOf(MaterialIcons.LANGUAGE));

        jLabel_Language.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_Language.setText("Language :");

        jComboBox_Language.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English" }));

        jLabel_ExpressSettingsIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(24f));
        jLabel_ExpressSettingsIcon.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_ExpressSettingsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ExpressSettingsIcon.setText(String.valueOf(MaterialIcons.BUILD));

        jLabel_ExpressSettings.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_ExpressSettings.setText("Express settings :");

        jCheckBox_ExpressSettings.setBackground(new java.awt.Color(250, 250, 250));
        jCheckBox_ExpressSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ExpressSettingsActionPerformed(evt);
            }
        });

        jLabel_HomePathIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(24f));
        jLabel_HomePathIcon.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_HomePathIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_HomePathIcon.setText(String.valueOf(MaterialIcons.FOLDER));

        jLabel_HomePath.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_HomePath.setText("MobyDroid Home Folder :");

        jTextField_HomePath.setEditable(false);

        jLabel_LogPathIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(24f));
        jLabel_LogPathIcon.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_LogPathIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LogPathIcon.setText(String.valueOf(MaterialIcons.LANGUAGE));

        jLabel_LogPath.setForeground(new java.awt.Color(97, 97, 97));
        jLabel_LogPath.setText("MobyDroid Log File Location :");

        jTextField_LogPath.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_LanguageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Language, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBox_Language, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_LogPathIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_LogPath, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField_LogPath, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_HomePathIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_HomePath, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField_HomePath, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_ExpressSettingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ExpressSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox_ExpressSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_ExpressSettingsIcon, jLabel_HomePathIcon, jLabel_LanguageIcon, jLabel_LogPathIcon});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_ExpressSettings, jLabel_HomePath, jLabel_Language, jLabel_LogPath});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Language, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_LanguageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Language, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ExpressSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ExpressSettingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_ExpressSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_HomePath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_HomePathIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_HomePath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_LogPath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_LogPathIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_LogPath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_ExpressSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ExpressSettingsActionPerformed
        // save value
        Settings.set("Express_Settings", String.valueOf(jCheckBox_ExpressSettings.isSelected()));
        Settings.save();
        // show warning
        JOptionPane.showMessageDialog(this, "You need to restart application for this change to take effect.", "Restart needed", JOptionPane.OK_OPTION, ResourceLoader.MaterialIcons_WARNING);
    }//GEN-LAST:event_jCheckBox_ExpressSettingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox_ExpressSettings;
    private javax.swing.JComboBox<String> jComboBox_Language;
    private javax.swing.JLabel jLabel_ExpressSettings;
    private javax.swing.JLabel jLabel_ExpressSettingsIcon;
    private javax.swing.JLabel jLabel_HomePath;
    private javax.swing.JLabel jLabel_HomePathIcon;
    private javax.swing.JLabel jLabel_Language;
    private javax.swing.JLabel jLabel_LanguageIcon;
    private javax.swing.JLabel jLabel_LogPath;
    private javax.swing.JLabel jLabel_LogPathIcon;
    private javax.swing.JTextField jTextField_HomePath;
    private javax.swing.JTextField jTextField_LogPath;
    // End of variables declaration//GEN-END:variables
}
