/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hq.mobydroid.gui;

import com.hq.materialdesign.MaterialIcons;

/**
 *
 * @author Bilux (i.bilux@gmail.com)
 */
public class JPanel_Home extends javax.swing.JPanel {

    // ************************ My variable ************************

    // *************************************************************

    /**
     * Creates new form JPanel_ManageApps
     *
     */
    public JPanel_Home() {
        // initialize components
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_AndroIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel_AndroIcon.setFont(MaterialIcons.ICON_FONT.deriveFont(128f));
        jLabel_AndroIcon.setForeground(new java.awt.Color(139, 195, 74));
        jLabel_AndroIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AndroIcon.setText(String.valueOf(MaterialIcons.ANDROID));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_AndroIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_AndroIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_AndroIcon;
    // End of variables declaration//GEN-END:variables
}
